{{- if and .Values.enabled .Values.pooler.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: {{ .Release.Name }}-pooler
  labels:
    app.kubernetes.io/name: postgresql-cluster
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  cluster:
    name: {{ .Release.Name }}

  instances: {{ .Values.pooler.instances }}
  type: {{ .Values.pooler.type }}

  pgbouncer:
    poolMode: {{ .Values.pooler.poolMode }}
    {{- if .Values.pooler.parameters }}
    parameters:
      {{- range $key, $value := .Values.pooler.parameters }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end }}

  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql-pooler
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers: []
{{- end }}
