{{- if .Values.enabled }}
{{- if .Values.superuserSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.superuserSecret.name }}
  labels:
    app.kubernetes.io/name: postgresql-cluster
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.superuserSecret.username }}
  {{- if .Values.superuserSecret.password }}
  password: {{ .Values.superuserSecret.password }}
  {{- else }}
  password: {{ randAlphaNum 32 | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.appSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appSecret.name }}
  labels:
    app.kubernetes.io/name: postgresql-cluster
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.appSecret.username }}
  {{- if .Values.appSecret.password }}
  password: {{ .Values.appSecret.password }}
  {{- else }}
  password: {{ randAlphaNum 32 | quote }}
  {{- end }}
{{- end }}
{{- end }}
