{{- if and .Values.jellyfin.tailscale.enabled .Values.jellyfin.tailscale.sidecar.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth-secret
  labels:
    {{- include "servarr.labels" (dict "context" . "appName" "jellyfin") | nindent 4 }}
type: Opaque
data:
    TS_AUTHKEY: {{ .Values.jellyfin.tailscale.sidecar.authKey | b64enc }}
{{- end }}
