{{- if and .Values.jellyfin.tailscale.enabled .Values.jellyfin.tailscale.sidecar.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth-secret
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: {{ .Release.Name }}-jellyfin
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
type: Opaque
data:
    TS_AUTHKEY: {{ .Values.jellyfin.tailscale.sidecar.authKey | b64enc }}
{{- end }}
