{{- if and .Values.emby.enabled .Values.emby.persistence.enabled (not .Values.emby.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-emby
  labels:
    {{- include "servarr.labels" (dict "context" . "appName" "emby") | nindent 4 }}
  {{- if .Values.emby.persistence.annotations }}
  annotations:
    {{- toYaml .Values.emby.persistence.annotations | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.emby.persistence.accessMode | quote }}
  {{- if .Values.emby.persistence.storageClass }}
  storageClassName: {{ .Values.emby.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.emby.persistence.size | quote }}
{{- end }}
