{{- if .Values.emby.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-emby
  labels:
    {{- include "servarr.labels" (dict "context" . "appName" "emby") | nindent 4 }}
spec:
  type: {{ .Values.emby.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.emby.service.port | default 8096 }}
      targetPort: http
      protocol: TCP
      name: http
{{ if (and (eq .Values.emby.service.type "NodePort") (not (empty .Values.emby.service.nodePort))) }}
      nodePort: {{.Values.emby.service.nodePort}}
{{ end }}
  selector:
    {{- include "servarr.selectorLabels" (dict "context" . "appName" "emby") | nindent 4 }}
{{- end }}
