{{- if and .Values.emby.enabled .Values.emby.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-emby
  labels:
    {{- include "servarr.labels" (dict "context" . "appName" "emby") | nindent 4 }}
  {{- with .Values.emby.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
