{{- if and .Values.sonarr.enabled .Values.sonarr.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-sonarr
  labels:
    {{- call "servarr.labels" "sonarr" | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-sonarr
  minReplicas: {{ .Values.sonarr.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.sonarr.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.sonarr.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.sonarr.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.sonarr.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.sonarr.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
