{{- if and .Values.sonarr.enabled .Values.sonarr.persistence.enabled (not .Values.sonarr.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-sonarr
  labels:
    {{- call "servarr.labels" "sonarr" | nindent 4 }}
  {{- if .Values.sonarr.persistence.annotations }}
  annotations:
    {{- toYaml .Values.sonarr.persistence.annotations | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.sonarr.persistence.accessMode | quote }}
  {{- if .Values.sonarr.persistence.storageClass }}
  storageClassName: {{ .Values.sonarr.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.sonarr.persistence.size | quote }}
{{- end }}
