{{- if and .Values.sonarr.enabled .Values.sonarr.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sonarr
  labels:
    {{- call "servarr.labels" "sonarr" | nindent 4 }}
  {{- with .Values.sonarr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
