{{- if and .Values.radarr.enabled .Values.radarr.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-radarr
  labels:
    {{- include "servarr.labels" (dict "context" . "appName" "radarr") | nindent 4 }}
  {{- with .Values.radarr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
