{{- if .Values.radarr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-radarr
  labels:
    {{- call "servarr.labels" "radarr" | nindent 4 }}
spec:
  type: {{ .Values.radarr.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.radarr.service.port | default 7878 }}
      targetPort: http
      protocol: TCP
      name: http
{{ if (and (eq .Values.radarr.service.type "NodePort") (not (empty .Values.radarr.service.nodePort))) }}
      nodePort: {{.Values.radarr.service.nodePort}}
{{ end }}
  selector:
    {{- call "servarr.selectorLabels" "radarr" | nindent 4 }}
{{- end }}
