{{- if and .Values.radarr.enabled .Values.radarr.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-radarr
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: {{ .Release.Name }}-radarr
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
  {{- with .Values.radarr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
