{{- if and .Values.jellyseerr.enabled .Values.jellyseerr.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-jellyseerr
  labels:
    {{- call "servarr.labels" "jellyseerr" | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-jellyseerr
  minReplicas: {{ .Values.jellyseerr.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.jellyseerr.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.jellyseerr.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.jellyseerr.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.jellyseerr.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.jellyseerr.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
