{{- if and .Values.jellyseerr.enabled .Values.jellyseerr.persistence.enabled (not .Values.jellyseerr.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-jellyseerr
  labels:
    {{- call "servarr.labels" "jellyseerr" | nindent 4 }}
  {{- if .Values.jellyseerr.persistence.annotations }}
  annotations:
    {{- toYaml .Values.jellyseerr.persistence.annotations | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.jellyseerr.persistence.accessMode | quote }}
  {{- if .Values.jellyseerr.persistence.storageClass }}
  storageClassName: {{ .Values.jellyseerr.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.jellyseerr.persistence.size | quote }}
{{- end }}
