{{- if .Values.jellyseerr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jellyseerr
  labels:
    {{- include "servarr.labels" (dict "context" . "appName" "jellyseerr") | nindent 4 }}
spec:
  type: {{ .Values.jellyseerr.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.jellyseerr.service.port | default 5055 }}
      targetPort: http
      protocol: TCP
      name: http
{{ if (and (eq .Values.jellyseerr.service.type "NodePort") (not (empty .Values.jellyseerr.service.nodePort))) }}
      nodePort: {{.Values.jellyseerr.service.nodePort}}
{{ end }}
  selector:
    {{- include "servarr.selectorLabels" (dict "context" . "appName" "jellyseerr") | nindent 4 }}
{{- end }}
