{{- if and .Values.jellyseerr.enabled .Values.jellyseerr.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-jellyseerr
  labels:
    {{- call "servarr.labels" "jellyseerr" | nindent 4 }}
  {{- with .Values.jellyseerr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
