{{- if .Values.jellyseerr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jellyseerr
  labels:
    app.kubernetes.io/name: jellyseerr
    app.kubernetes.io/instance: {{ .Release.Name }}-jellyseerr
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
spec:
  type: {{ .Values.jellyseerr.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.jellyseerr.service.port | default 5055 }}
      targetPort: http
      protocol: TCP
      name: http
{{ if (and (eq .Values.jellyseerr.service.type "NodePort") (not (empty .Values.jellyseerr.service.nodePort))) }}
      nodePort: {{.Values.jellyseerr.service.nodePort}}
{{ end }}
  selector:
    app.kubernetes.io/name: jellyseerr
    app.kubernetes.io/instance: {{ .Release.Name }}-jellyseerr
{{- end }}
