{{- if .Values.cleanuparr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cleanuparr
  labels:
    {{- call "servarr.labels" "cleanuparr" | nindent 4 }}
spec:
  type: {{ .Values.cleanuparr.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.cleanuparr.service.port | default 11011 }}
      targetPort: http
      protocol: TCP
      name: http
{{ if (and (eq .Values.cleanuparr.service.type "NodePort") (not (empty .Values.cleanuparr.service.nodePort))) }}
      nodePort: {{.Values.cleanuparr.service.nodePort}}
{{ end }}
  selector:
    {{- call "servarr.selectorLabels" "cleanuparr" | nindent 4 }}
{{- end }}
