{{- if and .Values.cleanuparr.enabled .Values.cleanuparr.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-cleanuparr
  labels:
    {{- call "servarr.labels" "cleanuparr" | nindent 4 }}
  {{- with .Values.cleanuparr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
