{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: crewai
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    {{- .Values.deployment.strategy | toYaml | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: crewai
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: crewai
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name | default (printf "%s" .Release.Name) }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s" .Release.Name) }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- if .Values.persistence.additionalVolumes }}
          {{- .Values.persistence.additionalVolumes | toYaml | nindent 8}}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /app/data
              name: data
          {{- if .Values.persistence.additionalMounts }}
            {{- .Values.persistence.additionalMounts | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- if .Values.crewai.openaiApiKey.existingSecret }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.crewai.openaiApiKey.existingSecret }}"
                  key: openai-api-key
            {{- else if .Values.crewai.openaiApiKey.value }}
            - name: OPENAI_API_KEY
              value: "{{ .Values.crewai.openaiApiKey.value }}"
            {{- end }}
            {{- if .Values.crewai.crewaiApiKey.existingSecret }}
            - name: CREWAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.crewai.crewaiApiKey.existingSecret }}"
                  key: crewai-api-key
            {{- else if .Values.crewai.crewaiApiKey.value }}
            - name: CREWAI_API_KEY
              value: "{{ .Values.crewai.crewaiApiKey.value }}"
            {{- end }}
            {{- if .Values.crewai.anthropicApiKey.existingSecret }}
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.crewai.anthropicApiKey.existingSecret }}"
                  key: anthropic-api-key
            {{- else if .Values.crewai.anthropicApiKey.value }}
            - name: ANTHROPIC_API_KEY
              value: "{{ .Values.crewai.anthropicApiKey.value }}"
            {{- end }}
            {{- if .Values.crewai.azureOpenaiApiKey.existingSecret }}
            - name: AZURE_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.crewai.azureOpenaiApiKey.existingSecret }}"
                  key: azure-openai-api-key
            {{- else if .Values.crewai.azureOpenaiApiKey.value }}
            - name: AZURE_OPENAI_API_KEY
              value: "{{ .Values.crewai.azureOpenaiApiKey.value }}"
            {{- end }}
            {{- if .Values.crewai.azureOpenaiEndpoint }}
            - name: AZURE_OPENAI_ENDPOINT
              value: "{{ .Values.crewai.azureOpenaiEndpoint }}"
            {{- end }}
            {{- if .Values.crewai.azureOpenaiApiVersion }}
            - name: AZURE_OPENAI_API_VERSION
              value: "{{ .Values.crewai.azureOpenaiApiVersion }}"
            {{- end }}
            - name: CREWAI_TELEMETRY
              value: "{{ .Values.crewai.telemetryEnabled }}"
            - name: LOG_LEVEL
              value: "{{ .Values.crewai.logLevel }}"
            {{- range $k,$v := .Values.crewai.extraEnv }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
