## Default production values for Outline

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt"
  rules:
    host: "outline.example.com"

# PostgreSQL persistence
postgresql:
  primary:
    persistence:
      storageClass: "ceph-rbd"

# Redis persistence
redis:
  master:
    persistence:
      storageClass: "ceph-rbd"

# Minio persistence
minio:
  persistence:
    storageClass: "ceph-rbd"
