{{- if and .Values.prowlarr.enabled .Values.prowlarr.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-prowlarr
  labels:
    {{- include "servarr.labels" (dict "context" . "appName" "prowlarr") | nindent 4 }}
  {{- with .Values.prowlarr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
