{{- if .Values.prowlarr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prowlarr
  labels:
    {{- include "servarr.labels" (dict "context" . "appName" "prowlarr") | nindent 4 }}
spec:
  type: {{ .Values.prowlarr.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.prowlarr.service.port | default 9696 }}
      targetPort: http
      protocol: TCP
      name: http
{{ if (and (eq .Values.prowlarr.service.type "NodePort") (not (empty .Values.prowlarr.service.nodePort))) }}
      nodePort: {{.Values.prowlarr.service.nodePort}}
{{ end }}
  selector:
    {{- include "servarr.selectorLabels" (dict "context" . "appName" "prowlarr") | nindent 4 }}
{{- end }}
