{{- if and .Values.qbittorrent.enabled .Values.qbittorrent.persistence.enabled (not .Values.qbittorrent.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-qbittorrent
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: {{ .Release.Name }}-qbittorrent
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
  {{- if .Values.qbittorrent.persistence.annotations }}
  annotations:
    {{- toYaml .Values.qbittorrent.persistence.annotations | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.qbittorrent.persistence.accessMode | quote }}
  {{- if .Values.qbittorrent.persistence.storageClass }}
  storageClassName: {{ .Values.qbittorrent.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.qbittorrent.persistence.size | quote }}
{{- end }}
---
{{- if and .Values.qbittorrent.enabled .Values.qbittorrent.localStorage.enabled (eq .Values.qbittorrent.localStorage.type "pvc") }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-qbittorrent-local-storage
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: {{ .Release.Name }}-qbittorrent
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
spec:
  accessModes:
    - {{ .Values.qbittorrent.localStorage.accessMode | quote }}
  {{- if .Values.qbittorrent.localStorage.storageClass }}
  storageClassName: {{ .Values.qbittorrent.localStorage.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.qbittorrent.localStorage.size | quote }}
{{- end }}
