{{- if and .Values.qbittorrent.enabled .Values.qbittorrent.persistence.enabled (not .Values.qbittorrent.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-qbittorrent
  labels:
    {{- call "servarr.labels" "qbittorrent" | nindent 4 }}
  {{- if .Values.qbittorrent.persistence.annotations }}
  annotations:
    {{- toYaml .Values.qbittorrent.persistence.annotations | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.qbittorrent.persistence.accessMode | quote }}
  {{- if .Values.qbittorrent.persistence.storageClass }}
  storageClassName: {{ .Values.qbittorrent.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.qbittorrent.persistence.size | quote }}
{{- end }}
