{{- if and .Values.qbittorrent.enabled .Values.qbittorrent.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-qbittorrent
  labels:
    {{- include "servarr.labels" (dict "context" . "appName" "qbittorrent") | nindent 4 }}
  {{- with .Values.qbittorrent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
