{{- if and .Values.sabnzbd.enabled .Values.sabnzbd.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sabnzbd
  labels:
    {{- call "servarr.labels" "sabnzbd" | nindent 4 }}
  {{- with .Values.sabnzbd.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
