{{- if .Values.sabnzbd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sabnzbd
  labels:
    {{- call "servarr.labels" "sabnzbd" | nindent 4 }}
spec:
  type: {{ .Values.sabnzbd.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.sabnzbd.service.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
{{ if (and (eq .Values.sabnzbd.service.type "NodePort") (not (empty .Values.sabnzbd.service.nodePort))) }}
      nodePort: {{.Values.sabnzbd.service.nodePort}}
{{ end }}
  selector:
    {{- call "servarr.selectorLabels" "sabnzbd" | nindent 4 }}
{{- end }}
