{{- if and .Values.bazarr.enabled .Values.bazarr.persistence.enabled (not .Values.bazarr.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-bazarr
  labels:
    {{- call "servarr.labels" "bazarr" | nindent 4 }}
  {{- if .Values.bazarr.persistence.annotations }}
  annotations:
    {{- toYaml .Values.bazarr.persistence.annotations | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.bazarr.persistence.accessMode | quote }}
  {{- if .Values.bazarr.persistence.storageClass }}
  storageClassName: {{ .Values.bazarr.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.bazarr.persistence.size | quote }}
{{- end }}
