{{- if and .Values.bazarr.enabled .Values.bazarr.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-bazarr
  labels:
    {{- include "servarr.labels" (dict "context" . "appName" "bazarr") | nindent 4 }}
  {{- with .Values.bazarr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
