{{- if .Values.bazarr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-bazarr
  labels:
    {{- call "servarr.labels" "bazarr" | nindent 4 }}
spec:
  type: {{ .Values.bazarr.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.bazarr.service.port | default 6767 }}
      targetPort: http
      protocol: TCP
      name: http
{{ if (and (eq .Values.bazarr.service.type "NodePort") (not (empty .Values.bazarr.service.nodePort))) }}
      nodePort: {{.Values.bazarr.service.nodePort}}
{{ end }}
  selector:
    {{- call "servarr.selectorLabels" "bazarr" | nindent 4 }}
{{- end }}
