{{- if and .Values.lidarr.enabled .Values.lidarr.persistence.enabled (not .Values.lidarr.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-lidarr
  labels:
    {{- include "servarr.labels" (dict "context" . "appName" "lidarr") | nindent 4 }}
  {{- if .Values.lidarr.persistence.annotations }}
  annotations:
    {{- toYaml .Values.lidarr.persistence.annotations | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.lidarr.persistence.accessMode | quote }}
  {{- if .Values.lidarr.persistence.storageClass }}
  storageClassName: {{ .Values.lidarr.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.lidarr.persistence.size | quote }}
{{- end }}
