{{- if and .Values.lidarr.enabled .Values.lidarr.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-lidarr
  labels:
    {{- include "servarr.labels" (dict "context" . "appName" "lidarr") | nindent 4 }}
  {{- with .Values.lidarr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
