{{- if .Values.lidarr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lidarr
  labels:
    {{- include "servarr.labels" (dict "context" . "appName" "lidarr") | nindent 4 }}
spec:
  type: {{ .Values.lidarr.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.lidarr.service.port | default 8686 }}
      targetPort: http
      protocol: TCP
      name: http
{{ if (and (eq .Values.lidarr.service.type "NodePort") (not (empty .Values.lidarr.service.nodePort))) }}
      nodePort: {{.Values.lidarr.service.nodePort}}
{{ end }}
  selector:
    {{- include "servarr.selectorLabels" (dict "context" . "appName" "lidarr") | nindent 4 }}
{{- end }}
