{{- if .Values.lidarr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lidarr
  labels:
    app.kubernetes.io/name: lidarr
    app.kubernetes.io/instance: {{ .Release.Name }}-lidarr
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
spec:
  type: {{ .Values.lidarr.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.lidarr.service.port | default 8686 }}
      targetPort: http
      protocol: TCP
      name: http
{{ if (and (eq .Values.lidarr.service.type "NodePort") (not (empty .Values.lidarr.service.nodePort))) }}
      nodePort: {{.Values.lidarr.service.nodePort}}
{{ end }}
  selector:
    app.kubernetes.io/name: lidarr
    app.kubernetes.io/instance: {{ .Release.Name }}-lidarr
{{- end }}
