{{- if and .Values.plex.enabled .Values.plex.persistence.enabled (not .Values.plex.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-plex
  labels:
    {{- call "servarr.labels" "plex" | nindent 4 }}
  {{- if .Values.plex.persistence.annotations }}
  annotations:
    {{- toYaml .Values.plex.persistence.annotations | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.plex.persistence.accessMode | quote }}
  {{- if .Values.plex.persistence.storageClass }}
  storageClassName: {{ .Values.plex.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.plex.persistence.size | quote }}
{{- end }}
