{{- if and .Values.plex.enabled .Values.plex.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-plex
  labels:
    {{- call "servarr.labels" "plex" | nindent 4 }}
  {{- with .Values.plex.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
