{{- if .Values.plex.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-plex
  labels:
    {{- call "servarr.labels" "plex" | nindent 4 }}
spec:
  type: {{ .Values.plex.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.plex.service.port | default 32400 }}
      targetPort: http
      protocol: TCP
      name: http
{{ if (and (eq .Values.plex.service.type "NodePort") (not (empty .Values.plex.service.nodePort))) }}
      nodePort: {{.Values.plex.service.nodePort}}
{{ end }}
  selector:
    {{- call "servarr.selectorLabels" "plex" | nindent 4 }}
{{- end }}
