{{- if .Values.flaresolverr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flaresolverr
  labels:
    {{- call "servarr.labels" "flaresolverr" | nindent 4 }}
spec:
  {{- if not .Values.flaresolverr.autoscaling.enabled }}
  replicas: {{ .Values.flaresolverr.replicaCount }}
  {{- end }}
  strategy:
    {{- .Values.flaresolverr.deployment.strategy | toYaml | nindent 4 }}
  selector:
    matchLabels:
      {{- call "servarr.selectorLabels" "flaresolverr" | nindent 6 }}
  template:
    metadata:
      {{- with .Values.flaresolverr.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- call "servarr.labels" "flaresolverr" | nindent 8 }}
    spec:
      {{- with .Values.flaresolverr.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.flaresolverr.serviceAccount.name | default (printf "%s-flaresolverr" .Release.Name) }}
      securityContext:
        {{- toYaml .Values.flaresolverr.podSecurityContext | nindent 8 }}
      {{- if .Values.flaresolverr.initContainers }}
      initContainers:
        {{- toYaml .Values.flaresolverr.initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.flaresolverr.securityContext | nindent 12 }}
          image: "{{ .Values.flaresolverr.image.repository }}:{{ .Values.flaresolverr.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.flaresolverr.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8191
              protocol: TCP
          resources:
            {{- toYaml .Values.flaresolverr.resources | nindent 12 }}
      {{- with .Values.flaresolverr.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flaresolverr.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flaresolverr.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
