{{- if .Values.flaresolverr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flaresolverr
  labels:
    {{- include "servarr.labels" (dict "context" . "appName" "flaresolverr") | nindent 4 }}
spec:
  type: {{ .Values.flaresolverr.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.flaresolverr.service.port | default 8989 }}
      targetPort: http
      protocol: TCP
      name: http
{{ if (and (eq .Values.flaresolverr.service.type "NodePort") (not (empty .Values.flaresolverr.service.nodePort))) }}
      nodePort: {{.Values.flaresolverr.service.nodePort}}
{{ end }}
  selector:
    {{- include "servarr.selectorLabels" (dict "context" . "appName" "flaresolverr") | nindent 4 }}
{{- end }}
