{{- if and .Values.flaresolverr.enabled .Values.flaresolverr.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-flaresolverr
  labels:
    {{- include "servarr.labels" (dict "context" . "appName" "flaresolverr") | nindent 4 }}
  {{- with .Values.flaresolverr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
