{{- if and .Values.flaresolverr.enabled .Values.flaresolverr.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-flaresolverr
  labels:
    app.kubernetes.io/name: flaresolverr
    app.kubernetes.io/instance: {{ .Release.Name }}-flaresolverr
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
  {{- with .Values.flaresolverr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
