{{- if .Values.local.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  config.yaml: |-
    tunnel: {{ required "The Cloudflare Tunnel Name is missing." .Values.local.auth.tunnelName }}
    credentials-file: /etc/cloudflared/tunnel-config.json
    warp-routing:
      enabled: {{ .Values.warpRouting }}
    ingress: {{ toYaml .Values.local.ingress | nindent 6 }}
{{- end }}